Release 1.4.0
IN-CORE/incore-lab pull request #104
Opened 2024-02-21 18:07 UTC by Vismayak

Do not merge this until the new packages get published to conda channel and update the config.yaml

2024-02-21 18:14 UTC, ywkim312 requested changes
No changelog updates?

2024-02-21 18:20 UTC, Vismayak commented
I was planning to do it when I update it to the main but will do now 👍

2024-02-22 20:08 UTC, ywkim312 commented on CHANGELOG.md
> +### Changed
Can you change the date to correct date? not 22?

2024-02-22 20:13 UTC, ywkim312 approved these changes

2024-02-22 20:30 UTC, merged